# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Common.proto',
  package='halodi.protobuf.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x43ommon.proto\x12\x16halodi.protobuf.common\"\x07\n\x05\x45mpty\"\x1a\n\tTimestamp\x12\r\n\x05stamp\x18\x01 \x01(\x03\"n\n\tDataChunk\x12\x1d\n\x15start_index_inclusive\x18\x01 \x01(\x05\x12\x1b\n\x13\x65nd_index_exclusive\x18\x02 \x01(\x05\x12\x17\n\x0ftotal_data_size\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x32\x63\n\x0c\x43ommonServer\x12S\n\rget_timestamp\x12\x1d.halodi.protobuf.common.Empty\x1a!.halodi.protobuf.common.Timestamp\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='halodi.protobuf.common.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=47,
)


_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='halodi.protobuf.common.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='halodi.protobuf.common.Timestamp.stamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=75,
)


_DATACHUNK = _descriptor.Descriptor(
  name='DataChunk',
  full_name='halodi.protobuf.common.DataChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_index_inclusive', full_name='halodi.protobuf.common.DataChunk.start_index_inclusive', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_index_exclusive', full_name='halodi.protobuf.common.DataChunk.end_index_exclusive', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_data_size', full_name='halodi.protobuf.common.DataChunk.total_data_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='halodi.protobuf.common.DataChunk.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=187,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Timestamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['DataChunk'] = _DATACHUNK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:halodi.protobuf.common.Empty)
  })
_sym_db.RegisterMessage(Empty)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:halodi.protobuf.common.Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

DataChunk = _reflection.GeneratedProtocolMessageType('DataChunk', (_message.Message,), {
  'DESCRIPTOR' : _DATACHUNK,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:halodi.protobuf.common.DataChunk)
  })
_sym_db.RegisterMessage(DataChunk)



_COMMONSERVER = _descriptor.ServiceDescriptor(
  name='CommonServer',
  full_name='halodi.protobuf.common.CommonServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=189,
  serialized_end=288,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_timestamp',
    full_name='halodi.protobuf.common.CommonServer.get_timestamp',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TIMESTAMP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMONSERVER)

DESCRIPTOR.services_by_name['CommonServer'] = _COMMONSERVER

# @@protoc_insertion_point(module_scope)
