# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ar_tools.Common_pb2 as Common__pb2


class CommonServerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_timestamp = channel.unary_unary(
                '/halodi.protobuf.common.CommonServer/get_timestamp',
                request_serializer=Common__pb2.Empty.SerializeToString,
                response_deserializer=Common__pb2.Timestamp.FromString,
                )


class CommonServerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def get_timestamp(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommonServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_timestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.get_timestamp,
                    request_deserializer=Common__pb2.Empty.FromString,
                    response_serializer=Common__pb2.Timestamp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'halodi.protobuf.common.CommonServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommonServer(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def get_timestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/halodi.protobuf.common.CommonServer/get_timestamp',
            Common__pb2.Empty.SerializeToString,
            Common__pb2.Timestamp.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
