# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ar_tools.Common_pb2 as Common__pb2
import ar_tools.Geometry_pb2 as Geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Image.proto',
  package='halodi.protobuf.sensors',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bImage.proto\x12\x17halodi.protobuf.sensors\x1a\x0c\x43ommon.proto\x1a\x0eGeometry.proto\"\x1f\n\x07Point2f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\xdd\x01\n\rImageMetadata\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\npixel_size\x18\x03 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x36\n\x0cimage_center\x18\x05 \x01(\x0b\x32 .halodi.protobuf.sensors.Point2f\x12\x39\n\x0f\x66ocal_length_px\x18\x06 \x01(\x0b\x32 .halodi.protobuf.sensors.Point2f\x12\t\n\x01k\x18\x07 \x03(\x02\x12\t\n\x01p\x18\x08 \x03(\x02\"J\n\x0eImagesMetadata\x12\x38\n\x08metadata\x18\x01 \x03(\x0b\x32&.halodi.protobuf.sensors.ImageMetadata2\xcd\x03\n\x0bImageServer\x12W\n\x0cget_metadata\x12\x1d.halodi.protobuf.common.Empty\x1a&.halodi.protobuf.sensors.ImageMetadata\"\x00\x12Y\n\rget_metadatas\x12\x1d.halodi.protobuf.common.Empty\x1a\'.halodi.protobuf.sensors.ImagesMetadata\"\x00\x12^\n\x0fget_sensor_pose\x12\x1d.halodi.protobuf.common.Empty\x1a*.halodi.protobuf.geometry.PoseWithMetadata\"\x00\x12Z\n\x14get_latest_timestamp\x12\x1d.halodi.protobuf.common.Empty\x1a!.halodi.protobuf.common.Timestamp\"\x00\x12N\n\x06stream\x12\x1d.halodi.protobuf.common.Empty\x1a!.halodi.protobuf.common.DataChunk\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[Common__pb2.DESCRIPTOR,Geometry__pb2.DESCRIPTOR,])




_POINT2F = _descriptor.Descriptor(
  name='Point2f',
  full_name='halodi.protobuf.sensors.Point2f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='halodi.protobuf.sensors.Point2f.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='halodi.protobuf.sensors.Point2f.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=101,
)


_IMAGEMETADATA = _descriptor.Descriptor(
  name='ImageMetadata',
  full_name='halodi.protobuf.sensors.ImageMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='halodi.protobuf.sensors.ImageMetadata.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='halodi.protobuf.sensors.ImageMetadata.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_size', full_name='halodi.protobuf.sensors.ImageMetadata.pixel_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='halodi.protobuf.sensors.ImageMetadata.encoding', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_center', full_name='halodi.protobuf.sensors.ImageMetadata.image_center', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='focal_length_px', full_name='halodi.protobuf.sensors.ImageMetadata.focal_length_px', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='halodi.protobuf.sensors.ImageMetadata.k', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='p', full_name='halodi.protobuf.sensors.ImageMetadata.p', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=325,
)


_IMAGESMETADATA = _descriptor.Descriptor(
  name='ImagesMetadata',
  full_name='halodi.protobuf.sensors.ImagesMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='halodi.protobuf.sensors.ImagesMetadata.metadata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=401,
)

_IMAGEMETADATA.fields_by_name['image_center'].message_type = _POINT2F
_IMAGEMETADATA.fields_by_name['focal_length_px'].message_type = _POINT2F
_IMAGESMETADATA.fields_by_name['metadata'].message_type = _IMAGEMETADATA
DESCRIPTOR.message_types_by_name['Point2f'] = _POINT2F
DESCRIPTOR.message_types_by_name['ImageMetadata'] = _IMAGEMETADATA
DESCRIPTOR.message_types_by_name['ImagesMetadata'] = _IMAGESMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point2f = _reflection.GeneratedProtocolMessageType('Point2f', (_message.Message,), {
  'DESCRIPTOR' : _POINT2F,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:halodi.protobuf.sensors.Point2f)
  })
_sym_db.RegisterMessage(Point2f)

ImageMetadata = _reflection.GeneratedProtocolMessageType('ImageMetadata', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMETADATA,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:halodi.protobuf.sensors.ImageMetadata)
  })
_sym_db.RegisterMessage(ImageMetadata)

ImagesMetadata = _reflection.GeneratedProtocolMessageType('ImagesMetadata', (_message.Message,), {
  'DESCRIPTOR' : _IMAGESMETADATA,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:halodi.protobuf.sensors.ImagesMetadata)
  })
_sym_db.RegisterMessage(ImagesMetadata)



_IMAGESERVER = _descriptor.ServiceDescriptor(
  name='ImageServer',
  full_name='halodi.protobuf.sensors.ImageServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=404,
  serialized_end=865,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_metadata',
    full_name='halodi.protobuf.sensors.ImageServer.get_metadata',
    index=0,
    containing_service=None,
    input_type=Common__pb2._EMPTY,
    output_type=_IMAGEMETADATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_metadatas',
    full_name='halodi.protobuf.sensors.ImageServer.get_metadatas',
    index=1,
    containing_service=None,
    input_type=Common__pb2._EMPTY,
    output_type=_IMAGESMETADATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_sensor_pose',
    full_name='halodi.protobuf.sensors.ImageServer.get_sensor_pose',
    index=2,
    containing_service=None,
    input_type=Common__pb2._EMPTY,
    output_type=Geometry__pb2._POSEWITHMETADATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_latest_timestamp',
    full_name='halodi.protobuf.sensors.ImageServer.get_latest_timestamp',
    index=3,
    containing_service=None,
    input_type=Common__pb2._EMPTY,
    output_type=Common__pb2._TIMESTAMP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stream',
    full_name='halodi.protobuf.sensors.ImageServer.stream',
    index=4,
    containing_service=None,
    input_type=Common__pb2._EMPTY,
    output_type=Common__pb2._DATACHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVER)

DESCRIPTOR.services_by_name['ImageServer'] = _IMAGESERVER

# @@protoc_insertion_point(module_scope)
